package br.com.ufjf.model.main;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Adminuser generated by hbm2java
 */
@Entity
@Table(name = "Adminuser", catalog = "collaborate"
)
public class Adminuser implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer idAdminuser;
    private String nameScientist;
    private String login;
    private String password;
    private String cpf;
    private String EMail;
    private String institution;

    public Adminuser() {
    }

    public Adminuser(String nameScientist, String login, String password, String cpf, String EMail, String institution) {
        this.nameScientist = nameScientist;
        this.login = login;
        this.password = password;
        this.cpf = cpf;
        this.EMail = EMail;
        this.institution = institution;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idAdminuser", unique = true, nullable = false)
    public Integer getIdAdminuser() {
        return this.idAdminuser;
    }

    public void setIdAdminuser(Integer idAdminuser) {
        this.idAdminuser = idAdminuser;
    }

    @Column(name = "nameScientist", nullable = false, length = 100)
    public String getNameScientist() {
        return this.nameScientist;
    }

    public void setNameScientist(String nameScientist) {
        this.nameScientist = nameScientist;
    }

    @Column(name = "login", nullable = false, length = 100)
    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @Column(name = "password", nullable = false, length = 100)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "CPF", nullable = false, length = 100)
    public String getCpf() {
        return this.cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Column(name = "E-mail", nullable = false, length = 100)
    public String getEMail() {
        return this.EMail;
    }

    public void setEMail(String EMail) {
        this.EMail = EMail;
    }

    @Column(name = "institution", nullable = false, length = 100)
    public String getInstitution() {
        return this.institution;
    }

    public void setInstitution(String institution) {
        this.institution = institution;
    }

}
