package br.com.ufjf.model.main;
// Generated 13/01/2014 11:59:13 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArtifactsUsed generated by hbm2java
 */
@Entity
@Table(name="ArtifactsUsed"
    ,catalog="collaborate"
)
public class ArtifactsUsed  implements java.io.Serializable {

private static final long serialVersionUID = 1L;
     private Integer idArtifactUsed;
     private int idWhere;
     private int idArtifact;
     private int idRationale;

    public ArtifactsUsed() {
    }

    public ArtifactsUsed(int idWhere, int idArtifact, int idRationale) {
       this.idWhere = idWhere;
       this.idArtifact = idArtifact;
       this.idRationale = idRationale;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idArtifactUsed", unique=true, nullable=false)
    public Integer getIdArtifactUsed() {
        return this.idArtifactUsed;
    }
    
    public void setIdArtifactUsed(Integer idArtifactUsed) {
        this.idArtifactUsed = idArtifactUsed;
    }

    
    @Column(name="idWhere", nullable=false)
    public int getIdWhere() {
        return this.idWhere;
    }
    
    public void setIdWhere(int idWhere) {
        this.idWhere = idWhere;
    }

    
    @Column(name="idArtifact", nullable=false)
    public int getIdArtifact() {
        return this.idArtifact;
    }
    
    public void setIdArtifact(int idArtifact) {
        this.idArtifact = idArtifact;
    }

    
    @Column(name="idRationale", nullable=false)
    public int getIdRationale() {
        return this.idRationale;
    }
    
    public void setIdRationale(int idRationale) {
        this.idRationale = idRationale;
    }




}


