package br.com.ufjf.model.main;
// Generated 13/01/2014 11:59:13 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Artifact generated by hbm2java
 */
@Entity
@Table(name="Artifact"
    ,catalog="collaborate"
)
public class Artifact  implements java.io.Serializable {

private static final long serialVersionUID = 1L;
     private Integer idArtifact;
     private String name;
     private String purpose;
     private String local;
     private String status;
     private String type;
     private char artifactType;

    public Artifact() {
    }

	
    public Artifact(String name, String local, String status, String type, char artifactType) {
        this.name = name;
        this.local = local;
        this.status = status;
        this.type = type;
        this.artifactType = artifactType;
    }
    public Artifact(String name, String purpose, String local, String status, String type, char artifactType) {
       this.name = name;
       this.purpose = purpose;
       this.local = local;
       this.status = status;
       this.type = type;
       this.artifactType = artifactType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idArtifact", unique=true, nullable=false)
    public Integer getIdArtifact() {
        return this.idArtifact;
    }
    
    public void setIdArtifact(Integer idArtifact) {
        this.idArtifact = idArtifact;
    }

    
    @Column(name="Name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Purpose", length=250)
    public String getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }

    
    @Column(name="Local", nullable=false, length=200)
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }

    
    @Column(name="Status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="type", nullable=false, length=100)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="artifactType", nullable=false, length=1)
    public char getArtifactType() {
        return this.artifactType;
    }
    
    public void setArtifactType(char artifactType) {
        this.artifactType = artifactType;
    }




}


