package br.com.ufjf.model.main;
// Generated 13/01/2014 11:59:13 by Hibernate Tools 3.6.0


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HowTable generated by hbm2java
 */
@Entity
@Table(name="HowTable"
    ,catalog="collaborate"
)
public class HowTable  implements java.io.Serializable {

private static final long serialVersionUID = 1L;
     private Integer idHow;
     private String description;

    public HowTable() {
    }

    public HowTable(String description) {
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idHow", unique=true, nullable=false)
    public Integer getIdHow() {
        return this.idHow;
    }
    
    public void setIdHow(Integer idHow) {
        this.idHow = idHow;
    }

    @Basic(optional = true) 
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


