package br.com.ufjf.model.main;
// Generated 13/01/2014 11:59:13 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Notes generated by hbm2java
 */
@Entity
@Table(name="Notes"
    ,catalog="collaborate"
)
@XmlRootElement
public class Notes  implements java.io.Serializable {

private static final long serialVersionUID = 1L;
     private Integer idNotes;
     private String description;
     private String subfeatures;
     private int idRationale;

    public Notes() {
    }

	
    public Notes(String description, int idRationale) {
        this.description = description;
        this.idRationale = idRationale;
    }
    public Notes(String description, String subfeatures, int idRationale) {
       this.description = description;
       this.subfeatures = subfeatures;
       this.idRationale = idRationale;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idNotes", unique=true, nullable=false)
    public Integer getIdNotes() {
        return this.idNotes;
    }
    
    public void setIdNotes(Integer idNotes) {
        this.idNotes = idNotes;
    }

    
    @Column(name="Description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="Subfeatures", length=200)
    public String getSubfeatures() {
        return this.subfeatures;
    }
    
    public void setSubfeatures(String subfeatures) {
        this.subfeatures = subfeatures;
    }

    
    @Column(name="idRationale", nullable=false)
    public int getIdRationale() {
        return this.idRationale;
    }
    
    public void setIdRationale(int idRationale) {
        this.idRationale = idRationale;
    }




}


