package br.com.ufjf.model.main;
// Generated 13/01/2014 11:59:13 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rationale generated by hbm2java
 */
@Entity
@Table(name="Rationale"
    ,catalog="collaborate"
)
public class Rationale  implements java.io.Serializable {

private static final long serialVersionUID = 1L;
     private Integer idRationale;
     private int idWho;
     private int idWhen;
     private int idWhere;
     private int idWhat;
     private int idHow;
     private Integer idNewRationale;

    public Rationale() {
    }

	
    public Rationale(int idWho, int idWhen, int idWhere, int idWhat, int idHow) {
        this.idWho = idWho;
        this.idWhen = idWhen;
        this.idWhere = idWhere;
        this.idWhat = idWhat;
        this.idHow = idHow;
    }
    public Rationale(int idWho, int idWhen, int idWhere, int idWhat, int idHow, Integer idNewRationale) {
       this.idWho = idWho;
       this.idWhen = idWhen;
       this.idWhere = idWhere;
       this.idWhat = idWhat;
       this.idHow = idHow;
       this.idNewRationale = idNewRationale;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idRationale", unique=true, nullable=false)
    public Integer getIdRationale() {
        return this.idRationale;
    }
    
    public void setIdRationale(Integer idRationale) {
        this.idRationale = idRationale;
    }

    
    @Column(name="idWho", nullable=false)
    public int getIdWho() {
        return this.idWho;
    }
    
    public void setIdWho(int idWho) {
        this.idWho = idWho;
    }

    
    @Column(name="idWhen", nullable=false)
    public int getIdWhen() {
        return this.idWhen;
    }
    
    public void setIdWhen(int idWhen) {
        this.idWhen = idWhen;
    }

    
    @Column(name="idWhere", nullable=false)
    public int getIdWhere() {
        return this.idWhere;
    }
    
    public void setIdWhere(int idWhere) {
        this.idWhere = idWhere;
    }

    
    @Column(name="idWhat", nullable=false)
    public int getIdWhat() {
        return this.idWhat;
    }
    
    public void setIdWhat(int idWhat) {
        this.idWhat = idWhat;
    }

    
    @Column(name="idHow", nullable=false)
    public int getIdHow() {
        return this.idHow;
    }
    
    public void setIdHow(int idHow) {
        this.idHow = idHow;
    }

    
    @Column(name="idNewRationale")
    public Integer getIdNewRationale() {
        return this.idNewRationale;
    }
    
    public void setIdNewRationale(Integer idNewRationale) {
        this.idNewRationale = idNewRationale;
    }




}


