package br.com.ufjf.model.main;
// Generated 13/01/2014 11:59:13 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WhatTable generated by hbm2java
 */
@Entity
@Table(name="WhatTable"
    ,catalog="collaborate"
)
public class WhatTable  implements java.io.Serializable {

private static final long serialVersionUID = 1L;
     private Integer idWhat;
     private String description;
     private String productName;
     private String purposeProduct;
     private String urlProduct;

    public WhatTable() {
    }

	
    public WhatTable(String description) {
        this.description = description;
    }
    public WhatTable(String description, String productName, String purposeProduct, String urlProduct) {
       this.description = description;
       this.productName = productName;
       this.purposeProduct = purposeProduct;
       this.urlProduct = urlProduct;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idWhat", unique=true, nullable=false)
    public Integer getIdWhat() {
        return this.idWhat;
    }
    
    public void setIdWhat(Integer idWhat) {
        this.idWhat = idWhat;
    }

    
    @Column(name="description", nullable=false, length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="ProductName", length=80)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="PurposeProduct")
    public String getPurposeProduct() {
        return this.purposeProduct;
    }
    
    public void setPurposeProduct(String purposeProduct) {
        this.purposeProduct = purposeProduct;
    }

    
    @Column(name="urlProduct", length=100)
    public String getUrlProduct() {
        return this.urlProduct;
    }
    
    public void setUrlProduct(String urlProduct) {
        this.urlProduct = urlProduct;
    }




}


