package br.com.ufjf.model.main;
// Generated 13/01/2014 11:59:13 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WhenTable generated by hbm2java
 */
@Entity
@Table(name="WhenTable"
    ,catalog="collaborate"
)
public class WhenTable  implements java.io.Serializable {

private static final long serialVersionUID = 1L;
     private Integer idWhen;
     private Integer day;
     private Integer month;
     private Integer year;
     private Integer time;
     private Integer minute;

    public WhenTable() {
    }

    public WhenTable(Integer day, Integer month, Integer year, Integer time, Integer minute) {
       this.day = day;
       this.month = month;
       this.year = year;
       this.time = time;
       this.minute = minute;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idWhen", unique=true, nullable=false)
    public Integer getIdWhen() {
        return this.idWhen;
    }
    
    public void setIdWhen(Integer idWhen) {
        this.idWhen = idWhen;
    }

    
    @Column(name="day")
    public Integer getDay() {
        return this.day;
    }
    
    public void setDay(Integer day) {
        this.day = day;
    }

    
    @Column(name="month")
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }

    
    @Column(name="year")
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }

    
    @Column(name="time")
    public Integer getTime() {
        return this.time;
    }
    
    public void setTime(Integer time) {
        this.time = time;
    }

    
    @Column(name="minute")
    public Integer getMinute() {
        return this.minute;
    }
    
    public void setMinute(Integer minute) {
        this.minute = minute;
    }




}


