package br.com.ufjf.model.main;
// Generated 13/01/2014 11:59:13 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WhereTable generated by hbm2java
 */
@Entity
@Table(name="WhereTable"
    ,catalog="collaborate"
)
public class WhereTable  implements java.io.Serializable {

private static final long serialVersionUID = 1L;
     private Integer idWhere;

    public WhereTable() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idWhere", unique=true, nullable=false)
    public Integer getIdWhere() {
        return this.idWhere;
    }
    
    public void setIdWhere(Integer idWhere) {
        this.idWhere = idWhere;
    }




}


