package br.com.ufjf.model.main;
// Generated 13/01/2014 11:59:13 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WhoTable generated by hbm2java
 */
@Entity
@Table(name="WhoTable"
    ,catalog="collaborate"
)
public class WhoTable  implements java.io.Serializable {

private static final long serialVersionUID = 1L;
     private Integer idWho;
     private int idScientist;

    public WhoTable() {
    }

    public WhoTable(int idScientist) {
       this.idScientist = idScientist;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idWho", unique=true, nullable=false)
    public Integer getIdWho() {
        return this.idWho;
    }
    
    public void setIdWho(Integer idWho) {
        this.idWho = idWho;
    }

    
    @Column(name="idScientist", nullable=false)
    public int getIdScientist() {
        return this.idScientist;
    }
    
    public void setIdScientist(int idScientist) {
        this.idScientist = idScientist;
    }




}


